distribution1:
  mean: [0, 5]
  cov: [[1, 0], [0, 1]]
  size: 100

distribution2:
  mean: [-5, -5]
  cov: [[2, 1], [1, 2]]
  size: 100

distribution3:
  mean: [-2, -5]
  cov: [[4, -1], [-1, 4]]
  size: 100

distribution4:
  mean: [2, 5]
  cov: [[1, -1], [-1, 1]]
  size: 100

distribution5:
  mean: [2, 2]
  cov: [[3, -1], [-1, 3]]
  size: 100